name: Go

on:  [ push, pull_request,workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.13','1.17','1.16' ]
    name: Go ${{ matrix.go }} sample
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: |
        go mod init
        go mod tidy
        go test -race -v .
